# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

num = 4000000

def getSumOfEvenValuedTerms(num):
    sum = 0
    termA, termB = 0, 1                                     # First 2 terms of the Fibonacci sequence
    termC = termA + termB                               # The first term to be processed
    while termC < num:
        if termC % 2 == 0:
            sum = sum + termC                             # Add the term if it is even
        termC = termC + termB
        termA, termB = termB, termA + termB
    return sum

# Print Output

print(getSumOfEvenValuedTerms(num))
